adamw: NoneType
agent_checkpoint: NoneType
avoid_eq_filters: false
beam: 20
bs: 1024
bushy: true
check_hint: true
cls: type/experiments/Neo_JOBRandomSplit1
cost_model: postgrescost
cross_entropy: false
db: imdbload
dedup_training_data: true
drop_cache: true
dropout: 0.0
early_stop_on_skip_fraction: NoneType
ema_decay: 0.95
engine: postgres
engine_dialect_query_dir: NoneType
epochs: 100
epsilon_greedy: 0
epsilon_greedy_random_plan: false
epsilon_greedy_random_transform: false
epsilon_greedy_within_beam_search: false
explore_soft_v: false
explore_visit_counts: false
explore_visit_counts_latency_sort: false
explore_visit_counts_sort: false
final_decay_rate: NoneType
finetune_out_mlp_only: false
generic_ops_only_for_min_card_cost: false
gradient_clip_val: 0
increment_iter_despite_timeouts: false
inherit_optimizer_state: false
init_experience: data/initial_policy_data.pkl
initial_timeout_ms: NoneType
l2_lambda: 0
label_transform_running_stats: false
label_transforms:
- log1p
- standardize
linear_decay_to_zero: false
loss_type: NoneType
lr: 0.001
lr_decay_iters: NoneType
lr_decay_rate: NoneType
lr_piecewise: NoneType
on_policy: false
param_noise: 0.0
param_tau: 1
per_transition_sgd_steps: -1
perturb_query_features: NoneType
physical_execution_hindsight: false
plan_physical: true
planner_config: NoneType
pos_embs: true
prev_replay_buffers_glob: NoneType
prev_replay_buffers_glob_val: NoneType
prev_replay_keep_last_fraction: 1
query_dir: queries/join-order-benchmark
query_glob:
- '*.sql'
real_use_plan_restrictions: true
reduce_lr_within_val_iter: false
relax_timeout_factor: NoneType
relax_timeout_on_n_timeout_iters: NoneType
replay_buffer_reset_at_iter: NoneType
run_baseline: false
search_method: beam_bk
search_space_join_ops:
- Hash Join
- Merge Join
- Nested Loop
search_space_scan_ops:
- Index Scan
- Index Only Scan
- Seq Scan
- Bitmap Heap Scan
- Tid Scan
search_until_n_complete_plans: 10
sim: false
sim_checkpoint: NoneType
sim_data_collection_intermediate_goals: true
sim_query_featurizer: true
sim_use_plan_restrictions: true
skip_sim_init_iter_1p: false
skip_training_on_expert: false
skip_training_on_timeouts: true
special_timeout_label: true
test_after_n_iters: 0
test_every_n_iters: 1
test_query_glob:
- 1c.sql
- 2c.sql
- 4b.sql
- 4c.sql
- 5c.sql
- 6a.sql
- 6c.sql
- 6e.sql
- 8b.sql
- 8c.sql
- 9c.sql
- 11d.sql
- 15a.sql
- 17b.sql
- 17e.sql
- 18b.sql
- 20a.sql
- 21a.sql
- 25c.sql
- 28b.sql
- 32b.sql
- 33a.sql
test_using_retrained_model: false
timeout_slack: 2
track_model_moving_averages: false
tree_conv: true
tree_conv_version: NoneType
update_label_stats_every_iter: true
use_adaptive_lr: NoneType
use_adaptive_lr_decay_to_zero: NoneType
use_cache: true
use_ema_source: false
use_last_n_iters: -1
use_local_execution: true
use_new_data_only: false
use_timeout: false
v2: true
val_iters: 100
validate_early_stop_patience: 3
validate_every_n_epochs: 5
validate_fraction: 0.1
