version: '3.9'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JOB_SETUP: ${JOB_SETUP}
    container_name: evaluation_suite
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JOB_SETUP: ${JOB_SETUP}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
