version: '3.9'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evaluation_suite
    environment:
      POSTGRES_USER: suite_user
      POSTGRES_PASSWORD: 71Vgfi4mUNPm
      POSTGRES_DB: suite_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
