version: '3.9'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evaluation_suite
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/app/db

volumes:
  db_data: